Added msft-windows-disable-copilot-and_recall.ps1
DTC-Inc/msp-script-library pull request #3
Opened 2024-06-18 16:30 UTC by coop-a-loop

Added msft-windows-disable-copilot-and_recall.ps1, which turns off Copilot, hides the Copilot taskbar icon and disables Recall

2024-06-19 09:10 UTC, nettts commented on msft-windows/msft-windows-disable-copilot-and-recall.ps1
> +Write-Host "Drive mapped to HKEY_USERS `n"
Can you remove this unix 'n? If you have this problem in the future, notepad++ or visual studio code.

2024-06-19 09:12 UTC, nettts commented on msft-windows/msft-windows-disable-copilot-and-recall.ps1
> +Write-Host "RMM: $RMM `n"
Remove "`n"

2024-06-19 09:13 UTC, nettts commented on msft-windows/msft-windows-disable-copilot-and-recall.ps1
> +Write-Host "Current Logged On User: $loggedOnUserName `n"
Remove "`n"

2024-06-19 09:15 UTC, nettts requested changes
There is some "`n" end of lines that need removed. I'm sure this is because of the text or code editor you were using before really getting into the code.

Or a copy paste from other sources. Doesn't matter. Just needs removed :).

2024-06-20 03:23 UTC, coop-a-loop commented
I wrote my code in PowerShell ISE and used 'n to insert a new line to
better format my output with the write-host command. Let me know if you
still want it removed.

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_special_characters?view=powershell-7.4

On Wed, Jun 19, 2024 at 5:15 AM Nate Smith ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> There is some "`n" end of lines that need removed. I'm sure this is
> because of the text or code editor you were using before really getting
> into the code.
>
> Or a copy paste from other sources. Doesn't matter. Just needs removed :).
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/DTC-Inc/msp-script-library/pull/3#pullrequestreview-2127624531>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BEVWFJSYR5PIBMRWWKRWNOLZIFD2XAVCNFSM6AAAAABJQMNKHSVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDCMRXGYZDINJTGE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-06-25 14:36 UTC, merged